### PR TITLE
bringing westeros, webrtc and all other changes

### PR DESCRIPTION
**Pull request by igor-borovkov**

### CODE REVIEW

**Comment by kraj** [comment]
when will this be proposed to wpe upstream ?

**Comment by igor-borovkov** [comment]
this repo was never used, everything it seems was going directly to WPE official repo, trying to push on using this repo...

**Comment by kraj** [comment]
I would rather suggest to keep using WPE upstream. Since we can collect cruft and never upstream it otherwise. Are there any patches we carry that needs to be upstreamed ?

**Comment by igor-borovkov** [comment]
We're pumping up development for WPE. You mean we should instead maintain a branch in Metro's official WPE git repo and hope that Metro doesn't delete that branch accidentally?

**Comment by kraj** [comment]
I am asking for more upstreaming process than fork is ok. If we dont have regular upstreaming then fork can go stale.

**Pull request merged**
